### PR TITLE
Images.save + ListedImages unit test

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #152 

Added Images.save(), unit test for ListedImages.iterate() and puzzles

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#155](https://github.com/amihaiemil/docker-java-api/issues/155) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#155` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#155](https://github.com/amihaiemil/docker-java-api/issues/155) is now out of scope

**Pull request merged**
