### PR TITLE
For #226: Implement ListedNetwork filters

### PR DESCRIPTION
**Pull request by paulodamaso**
For #226: Added test method for ListedNetworks.iterate

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#232](https://github.com/amihaiemil/docker-java-api/issues/232) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#232](https://github.com/amihaiemil/docker-java-api/issues/232) is assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/c3039c43-f7c4-4fce-888e-6640fa043722); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by bkuzmic** [comment]
@rultor merge it

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by amihaiemil** [comment]
@rultor try to merge again

**Comment by 0crat** [comment]
Job was finished in 40 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#232](https://github.com/amihaiemil/docker-java-api/issues/232) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
