### PR TITLE
For #275: Updating Copyright headers

### PR DESCRIPTION
**Pull request by bkuzmic**
For #275:

- Updating Copyright header's year, from `2018` to `2018-2019`.
- Adding Copyright headers to some files that didn't have it.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#281](https://github.com/amihaiemil/docker-java-api/issues/281) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#281](https://github.com/amihaiemil/docker-java-api/issues/281) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/9507c10b-c954-4ccd-a580-c0df766a255a); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31):

**Comment by 0crat** [comment]
The job [#281](https://github.com/amihaiemil/docker-java-api/issues/281) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
