### PR TITLE
(#154) Filters for ListedImages

### PR DESCRIPTION
**Pull request by llorllale**
This PR is for #154:
* Adds filtering capability for `ListedImages` according to [the docs](https://docs.docker.com/engine/api/v1.35/#operation/ImageList).

This PR took me way longer than it looks. The documentation referenced above is not entirely clear, and searches for some examples yield filters not included in the documentation(!) ([1](https://stackoverflow.com/questions/39976683/docker-api-can-t-apply-json-filters), [2](https://stackoverflow.com/a/49974198/1623885)).

I have not tested this solution against a live docker instance, and I'm not quite satisfied both with the efficiency of the unit test I wrote, nor with the elegance of both the implementation and test. `¯\_(ツ)_/¯` Maybe we can add a puzzle for that. Maybe we can also wait for #153 and make sure this actually works when we implement integration tests for that.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#159](https://github.com/amihaiemil/docker-java-api/issues/159) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#159](https://github.com/amihaiemil/docker-java-api/issues/159) is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/2721552437); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by llorllale** [comment]
@amihaiemil I can't be REV :)

**Comment by amihaiemil** [comment]
@llorllale well, looks ok. We'll see about integration testing, later. I boosted the original task 6x now, that is the maximum according to the Policy :D

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) everybody who has role `REV` is banned at [#159](https://github.com/amihaiemil/docker-java-api/issues/159); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#159](https://github.com/amihaiemil/docker-java-api/issues/159) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
