### PR TITLE
JsonResource improvements

### PR DESCRIPTION
**Pull request by sbespalov**
https://github.com/amihaiemil/docker-java-api/issues/202

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#220](https://github.com/amihaiemil/docker-java-api/issues/220) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#220](https://github.com/amihaiemil/docker-java-api/issues/220) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/e364d1f3-7441-4991-9f8c-d76fd6ee08cd); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#220](https://github.com/amihaiemil/docker-java-api/issues/220) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Pull request merged**
