### PR TITLE
RtLogs.follow() + unit test

### PR DESCRIPTION
**Pull request by amihaiemil**
Pr for #130

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#134](https://github.com/amihaiemil/docker-java-api/issues/134) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#134](https://github.com/amihaiemil/docker-java-api/issues/134) is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1590777725); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by amihaiemil** [comment]
@llorllale let's merge this, I want to advance with the project :D

**Comment by amihaiemil** [comment]
@rultor try to merge

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31):

**Comment by 0crat** [comment]
The job [#134](https://github.com/amihaiemil/docker-java-api/issues/134) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
