### PR TITLE
Adding pause and unpause features.

### PR DESCRIPTION
**Pull request by maviteixeira**
PR for #179 
Adding pause and unpause features.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#305](https://github.com/amihaiemil/docker-java-api/issues/305) is now in scope, role is `REV`

**Comment by maviteixeira** [comment]
I'm getting this error on my PR "Report submission to Coveralls API failed with HTTP status 405: Not Allowed", is this a common problem ? @amihaiemil

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#305` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#305](https://github.com/amihaiemil/docker-java-api/issues/305) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
