### PR TITLE
#299 unit tests for RtEvents

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #299

### CODE REVIEW

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) not enough funds available in the project, can't set budget of job [#342](https://github.com/amihaiemil/docker-java-api/issues/342), see [§21](http://www.zerocracy.com/policy.html#21); @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job [#342](https://github.com/amihaiemil/docker-java-api/issues/342) is not in the agenda of @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), can't set title

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Pull request merged**
