### PR TITLE
RtContainers, RtContainer started + puzzles

### PR DESCRIPTION
**Pull request by amihaiemil**
Pr for #28 

Started implementation of RtContainers and RtContainer.

### CODE REVIEW

**Comment by amihaiemil** [comment]
@rultor good to merge

**Comment by 0crat** [comment]
Job [#43](https://github.com/amihaiemil/docker-java-api/issues/43) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/amihaiemil/docker-java-api/issues/43#issuecomment-373074061))

@amihaiemil The job [#43](https://github.com/amihaiemil/docker-java-api/issues/43) is now out of scope

**Pull request merged**
