### PR TITLE
For #207: Added tests to volume filtering

### PR DESCRIPTION
**Pull request by paulodamaso**
For #207:
- Added filtering injection into `ListedVolumes`
- Created test to assure that `ListedVolumes` is filtering correctly the volumes

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#209](https://github.com/amihaiemil/docker-java-api/issues/209) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#209](https://github.com/amihaiemil/docker-java-api/issues/209) is assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/edda6763-3cd8-496d-a2ad-77b203b0ba91); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by bkuzmic** [comment]
@paulodamaso Alternative to the DockerFilters builder would be to create multiple small filter objects, like (from the Volumes API docs): DanglingFilter, LabelFilter, NameFilter, etc. and then just add them to the Set<DockerFilter>. I think that would be more EO's way and it would be more reusable to the other parts of API, like Images API. What do you think?

**Comment by bkuzmic** [comment]
@paulodamaso @amihaiemil I've created an example for filters on separate branch, so please take a look and comment.
This is the testcase:
[https://github.com/bkuzmic/docker-java-api/blob/test-for-filters/src/test/java/com/amihaiemil/docker/filters/DockerFiltersTestCase.java](https://github.com/bkuzmic/docker-java-api/blob/test-for-filters/src/test/java/com/amihaiemil/docker/filters/DockerFiltersTestCase.java)
and here you'll find implementation:
[https://github.com/bkuzmic/docker-java-api/tree/test-for-filters/src/main/java/com/amihaiemil/docker/filters](https://github.com/bkuzmic/docker-java-api/tree/test-for-filters/src/main/java/com/amihaiemil/docker/filters)

**Comment by amihaiemil** [comment]
@paulodamaso Well, I also don't know why the ``Set<Volume>`` -- see how [ListedImages](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/ListedImages.java) does the filtering, I suppose it should be the same, isn't that right? cc: @bkuzmic

**Comment by bkuzmic** [comment]
@amihaiemil @paulodamaso From my side, idea was to make this reusable in a more OO way, in a sense that I would not like to copy Map\<String,Iterable\<String\>\> in every implementation. Plus, with the OO way, we can make validation of the filters easier.

**Comment by amihaiemil** [comment]
@bkuzmic Right, I'll have a look over your proposal a bit later :)

**Comment by paulodamaso** [comment]
@bkuzmic I've liked they way you implemented it. But if we are thinking in implementing a reusable filter maybe we should try to create some generic filter which applies some filtering function to its results, something like `Func<Iterable<T>, Iterable<T>`. Does this sounds good or it's a stupid idea?

Oh, and about `Set<Volume>` I still don't understand why we use a map for the filters: what would be the `key` of this map? So I've just put all values on a `Set`.

**Comment by amihaiemil** [comment]
@bkuzmic  

> I've created an example for filters on separate branch, so please take a look and comment.

They look alright, I guess, but do we need this ``Filter`` abstraction that much? Why can't we simply use a map, like now?

@paulodamaso 

> Oh, and about Set<Volume> I still don't understand why we use a map for the filters: what would be the key of this map? So I've just put all values on a Set.

We use a map because it's easier to parse (the API expects a map in the query string anyway). The key is the attribute for which you filter and the value is the expected valud of that attribute. 

and

> But if we are thinking in implementing a reusable filter maybe we should try to create some generic filter which applies some filtering function to its results, something like Func<Iterable<T>, Iterable<T>

Yes, sounds good -- but the question is: when/how do we apply this Function? So far it sounds that you will apply it **after** fetching **all** entitites. In other words, we do the filtering ourselfs in memory, instead of asking Docker to do it for us.

**Comment by amihaiemil** [comment]
@paulodamaso I think we're taking too long on this ticket :( 

Can you just add a filtering, like in ListedImages and we'll discuss refactoring in a future ticket? Leave a puzzle for it :D

**Comment by paulodamaso** [comment]
@bkuzmic @amihaiemil After all the discussion, added the `Map<String, Iterable<String>>` filter and made the test

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@bkuzmic Please take a look now

**Comment by bkuzmic** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@rultor merge it

**Pull request merged**
