### PR TITLE
Containers.all() + unit test

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #161, added option to fetch all containers, not only the running ones.

### CODE REVIEW

**Comment by amihaiemil** [comment]
@wem Here is the PR with the changes, WDYT? 

Actually, this is not the most correct solution (from an object-oriented perspective). We should in fact have a new implementation of the Containers interface (we would then have 2 implementations: RunningContainers and AllContainers)... but let's leave it like this for now, maybe we'll change it later.

**Comment by 0crat** [comment]
Job [#162](https://github.com/amihaiemil/docker-java-api/issues/162) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#162](https://github.com/amihaiemil/docker-java-api/issues/162) is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/7701f9e1-d548-4cac-983d-d5124ed3ad87); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by amihaiemil** [comment]
@llorllale I updated the Javadocs. I don't want ot leave a puzzle now, since I'm not sure it's a good idea entirely... I'll think about it and we see later :)

**Comment by llorllale** [comment]
@amihaiemil ok, looks good then

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#162](https://github.com/amihaiemil/docker-java-api/issues/162) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Pull request merged**
