### PR TITLE
For #269: Implementing Plugin enable() and disable() methods

### PR DESCRIPTION
**Pull request by bkuzmic**
For #269:

- Implementing enable and disable methods
- Fixing tests

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#279](https://github.com/amihaiemil/docker-java-api/issues/279) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#279](https://github.com/amihaiemil/docker-java-api/issues/279) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/cabe9255-0dc2-4bb5-ac35-a2c9b9f2c5c3); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by amihaiemil** [comment]
@bkuzmic looks good, thanks! :)

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job was finished in 21 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31):

**Pull request merged**
