### PR TITLE
(#79) Draft for sending responses back to clients from the mock UnixServer

### PR DESCRIPTION
**Pull request by llorllale**
This PR:
* Advances work for #79 
* Leaves puzzle for finishing touches and testing

References:
* [RFC-2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html)
* My own sample taken with wireshark showing structure of a simple response from a random web page:
```
HTTP/1.1 200 OK
Content-Type: application/json
Date: Thu, 12 Apr 2018 13:43:53 GMT
Content-Length: 951

[some random json]
```

### CODE REVIEW

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by amihaiemil** [comment]
@rultor good to merge

**Comment by amihaiemil** [comment]
@rultor merge again

**Comment by 0crat** [comment]
The job [#81](https://github.com/amihaiemil/docker-java-api/issues/81) is now out of scope

**Comment by amihaiemil** [comment]
@llorllale where did you say you got a puzzle formatting wrong? I can't find that comment anymore :D

**Comment by llorllale** [comment]
@amihaiemil I did it after @0pdd's error [here](https://github.com/amihaiemil/docker-java-api/commit/16f300c24a60f1e152e0770a29b915d4b9bd2da5#commitcomment-28581345)

**Pull request merged**
