### PR TITLE
For #213 Creating volumes with parameters

### PR DESCRIPTION
**Pull request by bkuzmic**
For #213: 

- creating volumes with parameters like driver, driver options and labels
- also returning proper Volume object on create.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#262](https://github.com/amihaiemil/docker-java-api/issues/262) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#262](https://github.com/amihaiemil/docker-java-api/issues/262) is assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/67b71884-32ae-4904-bcca-77c0577d1be0); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by bkuzmic** [comment]
@amihaiemil Is this a 0crat bug? I am asked to do the review of my own PR :)

**Comment by amihaiemil** [comment]
@bkuzmic seems like it, yes. Can you submit it to zerocrat/farm? You should get paid if you are a member there :)

**Comment by bkuzmic** [comment]
@rultor merge it.

**Comment by amihaiemil** [comment]
@rultor good to merge

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
The job [#262](https://github.com/amihaiemil/docker-java-api/issues/262) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
