### PR TITLE
#299 Events/RtEvents implemented; needs tests

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #299 

We cannot expose a Stream directly, we need to let the user specify the query parameters as well. Thus, we need the ``Events`` abstraction.

Still needs unit tests.

### CODE REVIEW

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#340` is not assigned, can't get performer

**Pull request merged**
