### PR TITLE
For #276: Implementing Images importImage() method

### PR DESCRIPTION
**Pull request by bkuzmic**
For #276:

- Implementing `importImage` method.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#282](https://github.com/amihaiemil/docker-java-api/issues/282) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@bkuzmic looks good, thanks!

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31):

**Comment by 0crat** [comment]
The job [#282](https://github.com/amihaiemil/docker-java-api/issues/282) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
