### PR TITLE
Added ListedImages and made RtImages abstract

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #144 

RtImages is abstract since we will have at least 2 implementations: ``ListedImages`` and ``SearchedImages``, which will be iterated differently (use a different HTTP endpont).

Left a few puzzles for continuing implementation in different areas.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#151](https://github.com/amihaiemil/docker-java-api/issues/151) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@rultor merge pls

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#151` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#151](https://github.com/amihaiemil/docker-java-api/issues/151) is now out of scope

**Pull request merged**
