### PR TITLE
For #237 Implemented listing Networks with filters

### PR DESCRIPTION
**Pull request by bkuzmic**
For #237:

- Implemented listing Networks using filters

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#246](https://github.com/amihaiemil/docker-java-api/issues/246) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#246](https://github.com/amihaiemil/docker-java-api/issues/246) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/b3caf5d3-ef6f-4f22-8f15-94f0ad98b976); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@amihaiemil ping

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
The job [#246](https://github.com/amihaiemil/docker-java-api/issues/246) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
