### PR TITLE
For #283: Creating StringPayloadOf class for tests

### PR DESCRIPTION
**Pull request by bkuzmic**
For #283:

- Creating new class `StringPayloadOf` to help minimize test code duplication

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#289](https://github.com/amihaiemil/docker-java-api/issues/289) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@bkuzmic looks good, thanks!

**Comment by amihaiemil** [comment]
@rultor mege it

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
The job [#289](https://github.com/amihaiemil/docker-java-api/issues/289) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
