### PR TITLE
RenamedFiles

### PR DESCRIPTION
**Pull request by irinil**
Renamed LocalDocker to LocalUnixDocker and RemoteDocker to RemoteTcpDocker.

### CODE REVIEW

**Comment by amihaiemil** [comment]
@irinil Thanks for the PR. However, two comments: I think we should simply drop the ``Local`` and ``Remote`` prefixes. At least in the case of normal TCP socket, the Docker instance can also be local (on Windows). 

So I think ``UnixDocker`` and ``TcpDocker`` are better names.

One other thing is that we should not remove ``LocalDocker`` and ``RemoteDocker`` right away. We should deprecate them, add comprehensive JavaDocs telling the user about the change, and only remove them in a later version.

**Comment by irinil** [comment]
@amihaiemil  Ok! Thank you for the comments! So for the deprecation I just need to use the @Deprecated annotation and add the JavaDocs?

**Comment by amihaiemil** [comment]
@irinil Yes, here is an example: https://github.com/decorators-squad/eo-yaml/blob/master/src/main/java/com/amihaiemil/eoyaml/YamlNode.java#L49

So there is the ``@Deprecated`` annotation and also the ``@deprecated`` JavaDoc tag.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) not enough funds available in the project, can't set budget of job [#328](https://github.com/amihaiemil/docker-java-api/issues/328), see [§21](http://www.zerocracy.com/policy.html#21); @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by amihaiemil** [comment]
@irinil Can you fix the CI build? It has an error reported by Checkstyle: 

```
[ERROR] /home/travis/build/amihaiemil/docker-java-api/src/main/java/com/amihaiemil/docker/LocalDocker.java:55:1: Line contains a tab character. [FileTabCharacter]
```

TABs are not allowed in the code. Instead of TAB, use 4-space indentation :D

**Comment by irinil** [comment]
Yes of course I will fix it!

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by amihaiemil** [comment]
@irinil Thank you so much!

**Comment by 0crat** [comment]
Job [#328](https://github.com/amihaiemil/docker-java-api/issues/328) is not in the agenda of @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), can't retrieve data and time of add

**Pull request merged**
