### PR TITLE
For #206. Adding prune method to Volumes

### PR DESCRIPTION
**Pull request by bkuzmic**
For #206:
- added prune method to Volumes 
- added unit tests for RtVolumes

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#210](https://github.com/amihaiemil/docker-java-api/issues/210) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@bkuzmic @paulodamaso looks good, thanks! :) for the future, I don't think imports have to be in alphabetic order, we can skip this kind of cosmetic stuff.

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31):

**Comment by 0crat** [comment]
The job [#210](https://github.com/amihaiemil/docker-java-api/issues/210) is now out of scope

**Comment by paulodamaso** [comment]
@amihaiemil I did not received reputation payment for this one

**Comment by paulodamaso** [comment]
@amihaiemil no problem

**Pull request merged**
