### PR TITLE
Implemented docker.info()

### LINKED ISSUE #344: Implement Docker.info() endpoint
This method will return the ``Info`` we got from calling the ``GET /info`` endpoint.

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #344 

* implemented ``Info :: docker.info()``
* added unit tests and integration test
* also added missing integration test for ``docker.version()``

### CODE REVIEW

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) not enough funds available in the project, can't set budget of job [#345](https://github.com/amihaiemil/docker-java-api/issues/345), see [§21](http://www.zerocracy.com/policy.html#21); @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Job [#345](https://github.com/amihaiemil/docker-java-api/issues/345) is closed, can't start order

**Comment by 0crat** [comment]
Job [#345](https://github.com/amihaiemil/docker-java-api/issues/345) is not in the agenda of @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), can't set title

**Pull request merged**
