### PR TITLE
RemoteDocker authentication

### PR DESCRIPTION
**Pull request by sbespalov**
https://github.com/amihaiemil/docker-java-api/issues/193

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#219](https://github.com/amihaiemil/docker-java-api/issues/219) is now in scope, role is `REV`

**Comment by bkuzmic** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job was finished in 4 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#219](https://github.com/amihaiemil/docker-java-api/issues/219) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#219` doesn't exist in WBS, can't create order

**Pull request merged**
