### PR TITLE
Fixing #186

### PR DESCRIPTION
**Pull request by bkuzmic**
PR for #186. Since this is old task, removing puzzle and trying to close it using PR.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#198](https://github.com/amihaiemil/docker-java-api/issues/198) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#198` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#198](https://github.com/amihaiemil/docker-java-api/issues/198) is now out of scope

**Pull request merged**
