### PR TITLE
Container.logs() + unit tests

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #128 

Added and unit tested ``Container.logs()`` and left puzzle to continue

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#129](https://github.com/amihaiemil/docker-java-api/issues/129) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#129](https://github.com/amihaiemil/docker-java-api/issues/129) is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1551019685); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by llorllale** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#129](https://github.com/amihaiemil/docker-java-api/issues/129) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
