### PR TITLE
For #225: Implement the rest of Network methods

### PR DESCRIPTION
**Pull request by paulodamaso**
For #225: Added test methods for Network.connect and Network.disconnect

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#231](https://github.com/amihaiemil/docker-java-api/issues/231) is now in scope, role is `REV`

**Comment by bkuzmic** [comment]
@amihaiemil I think that puzzle number 231 is interfering with pull request 231. How to properly number the puzzle to avoid collision?

**Comment by bkuzmic** [comment]
@paulodamaso @amihaiemil Adding tests and just ignoring them just feels wrong to me. I would rather create a partial implementation (or fake) that would make the test pass. This is not TDD and it doesn't give the developer immediate feedback of the correctness of the test or implementation.
If someone forgets to remove the `@Ignore` annotation, it would seem that everything is ok.
Regarding the dropping of the coverage - in the future I'll avoid adding dummy unsupported operation methods and just leave the puzzle to implement the interface. WDYT?

**Comment by paulodamaso** [comment]
@bkuzmic I think that creating a partial or fake implementation that makes the test pass is worst, because it will give the impression that everythin is ok, even with "incorrect" code. I agree that leaving an `@Ignore` isn't the best solution, but rearely the 30min timeframe allows us to create test and code; that's where pdd kicks in, because we are allowed to decompose the task. Please note that in every puzzle left after the implementation of a test we must declare that the tests should be un-igonred, so if the developer just forgets to remove the annotation he is forgetting to resolve the task.

**Comment by bkuzmic** [comment]
@paulodamaso Well, if you follow the TDD principles strictly (just to be clear, I'm not a fan of strict TDD), then it is ok to write a smallest peace of code to make a test pass and then refactor the test and then change the implementation again. Basically, this is what I've done when I created tests for all the "UnsupportedOperationException" methods.
I understand your point about the comments in the puzzle and timeframe, but I would rather force the developer to create a test that will pass (preferably by refactoring the test for UnsupportedOperationException).
Let's just conclude with the statement that I don't like comments in the source code :)

**Comment by bkuzmic** [comment]
@paulodamaso Btw. do you know the answer to the question:

> @amihaiemil I think that puzzle number 231 is interfering with pull request 231. How to properly number the puzzle to avoid collision?

**Comment by bkuzmic** [comment]
@rultor merge it.

**Comment by paulodamaso** [comment]
@bkuzmic Just for the record:
> Well, if you follow the TDD principles strictly (just to be clear, I'm not a fan of strict TDD), then it is ok to write a smallest peace of code to make a test pass and then refactor the test and then change the implementation again. Basically, this is what I've done when I created tests for all the 
"UnsupportedOperationException" methods.
I understand your point about the comments in the puzzle and timeframe, but I would rather force the developer to create a test that will pass (preferably by refactoring the test for UnsupportedOperationException).
Writing the test first helps us to define the requirements of our code, and we just skip the step of creating fake or mock tests for our code. Note that when we create a code that does not work and then a test just to fullfill the coverage requirements (that tests a wroing behavior) we end up with two problems, a code that does not what it was supposed to and a test that does not test the correct behavior of the code.
>Let's just conclude with the statement that I don't like comments in the source code :)
Me neither! But puzzles are not comments; in 0pdd implementation we use some special tag to define them, but talking about strict XDSD we could open these issues concurrently to our tickets in our issue base; 0pdd and its syntax is just a tool to ease the job decomposition

**Comment by amihaiemil** [comment]
@bkuzmic 

> I think that puzzle number 231 is interfering with pull request 231. How to properly number the puzzle to avoid collision?

I also don't understand your question :) 
Github assigns Issue/PR numbers automatically, we simply specify the parent-issue in a new Puzzle, that's it. Or am I missing something?

**Comment by bkuzmic** [comment]
@amihaiemil Ok, I got it all wrong. I thought that I needed to increment a puzzle number to next higher number. My mistake, sorry :-(.

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
The job [#231](https://github.com/amihaiemil/docker-java-api/issues/231) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
