### PR TITLE
#67 path to certs

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #67 
Added Path to certificates and puzzle for continuing

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#89](https://github.com/amihaiemil/docker-java-api/issues/89) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#89](https://github.com/amihaiemil/docker-java-api/issues/89) is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1151844963); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by llorllale** [comment]
@rultor good to merge

@amihaiemil sorry for the delay - these past few weeks were really busy for me

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@llorllale No problem for the delay. I also work a little less on OSS these weeks since I am busy with my fulltime job :(

**Comment by amihaiemil** [comment]
@rultor merge it pls

**Comment by amihaiemil** [comment]
@rultor merge it pls

**Comment by amihaiemil** [comment]
@llorllale I wonder where the compilation error comes from... I'll have a look later :D

**Comment by 0crat** [comment]
The user @llorllale[/z](https://www.0crat.com/u/llorllale) resigned from [#89](https://github.com/amihaiemil/docker-java-api/issues/89), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by amihaiemil** [comment]
@0crat assign @llorllale

**Comment by 0crat** [comment]
> @0crat assign @llorllale  ([here](https://github.com/amihaiemil/docker-java-api/issues/89#issuecomment-387306340))

@amihaiemil This pull request [#89](https://github.com/amihaiemil/docker-java-api/issues/89) is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1280743645); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by amihaiemil** [comment]
@llorllale sorry for the delay and lost points. I reassigned you manually so now, at least, you are at 0 :D

**Comment by 0crat** [comment]
The job [#89](https://github.com/amihaiemil/docker-java-api/issues/89) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
