### PR TITLE
(#41) Draft for a UnixSocketServer implementation

### PR DESCRIPTION
**Pull request by llorllale**
This PR:
* solves #41 
* Drafts an implementation for a unix socket server in `UnixServer`
* Leaves a puzzle for continuing implementation

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#78](https://github.com/amihaiemil/docker-java-api/issues/78) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#78](https://github.com/amihaiemil/docker-java-api/issues/78) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/941378052); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by llorllale** [comment]
@amihaiemil so what's wrong with rultor?

**Comment by amihaiemil** [comment]
@llorllale not sure, I did not modify ``rultor.yml`` or anything recently. I think there is either a bug in Rultor or some bug introduced in Yegor's java8 Docker image... I opened an issue: https://github.com/yegor256/rultor/issues/1253

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#78](https://github.com/amihaiemil/docker-java-api/issues/78) is now out of scope

**Pull request merged**
