### PR TITLE
MatchStatus + unit tests

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #93 
Left puzzle for using this handler to reduce code duplication.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#104](https://github.com/amihaiemil/docker-java-api/issues/104) is now in scope, role is `REV`

**Comment by llorllale** [comment]
@rultor good to merge

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#104](https://github.com/amihaiemil/docker-java-api/issues/104) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
