### PR TITLE
Encrypted new configs

### LINKED ISSUE #318: 401 Unauthorized when trying to Deploy to Nexus
Let's try to fix this

### PR DESCRIPTION
**Pull request by amihaiemil**
Should help with #318

### CODE REVIEW

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by amihaiemil** [comment]
@rultor try to merge again

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#319` is not assigned, can't get performer

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
