### PR TITLE
For #170: Added tests to Images.import

### PR DESCRIPTION
**Pull request by paulodamaso**
For #170: 
- Added test to Images.import
- Left todo for continue to implement Images methods

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#249](https://github.com/amihaiemil/docker-java-api/issues/249) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#249](https://github.com/amihaiemil/docker-java-api/issues/249) is assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/579c4f41-dd27-4429-84ce-a0ccd605e442); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#249` already assigned to @bkuzmic, can't assign to @bkuzmic

**Comment by bkuzmic** [comment]
@rultor merge it.

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 26 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#249](https://github.com/amihaiemil/docker-java-api/issues/249) is now out of scope

**Pull request merged**
