### PR TITLE
(#109) RtContainers.create(): URL encode the query parameters

### PR DESCRIPTION
**Pull request by llorllale**
This PR:
* solves #109

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#119](https://github.com/amihaiemil/docker-java-api/issues/119) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) everybody who has role `REV` is banned at [#119](https://github.com/amihaiemil/docker-java-api/issues/119); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by amihaiemil** [comment]
@llorllale nice, I like it. But there is a conflict in RtContainers, could you fix it? :D

**Comment by llorllale** [comment]
@amihaiemil fixed conflicts

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#119](https://github.com/amihaiemil/docker-java-api/issues/119) is now out of scope

**Pull request merged**
