### PR TITLE
mock Response.toString() + unit test

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #87

### CODE REVIEW

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job [#141](https://github.com/amihaiemil/docker-java-api/issues/141) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#141` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#141](https://github.com/amihaiemil/docker-java-api/issues/141) is now out of scope

**Pull request merged**
