### PR TITLE
Add integration tests for filters

### PR DESCRIPTION
**Pull request by maviteixeira**
Add integration tests for filters.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#306](https://github.com/amihaiemil/docker-java-api/issues/306) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#306` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#306](https://github.com/amihaiemil/docker-java-api/issues/306) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
