### PR TITLE
(#103) Implemented Image.tag()

### PR DESCRIPTION
**Pull request by llorllale**
This PR:
* solves #103 
* uses the [ImageTag Docs](https://docs.docker.com/engine/api/v1.35/#operation/ImageTag) as reference
* Implements `Image.tag()`

### CODE REVIEW

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) everybody who has role `REV` are banned at [#112](https://github.com/amihaiemil/docker-java-api/issues/112); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by amihaiemil** [comment]
@llorllale looks nice

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by 0crat** [comment]
This pull request [#112](https://github.com/amihaiemil/docker-java-api/issues/112) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1361949520); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#112](https://github.com/amihaiemil/docker-java-api/issues/112) is now out of scope

**Pull request merged**
