### PR TITLE
For #243: Adding filters to FilteredUriBuilder

### PR DESCRIPTION
**Pull request by bkuzmic**
For #243:

- implementing adding Json filters to FilteredUriBuilder

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#253](https://github.com/amihaiemil/docker-java-api/issues/253) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#253](https://github.com/amihaiemil/docker-java-api/issues/253) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/61260078-2513-438d-ae9d-201c1c3fda1d); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job was finished in 22 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Pull request merged**
