### PR TITLE
#296 events() first sketch

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #296 

Added a first verison of events monitoring.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#297](https://github.com/amihaiemil/docker-java-api/issues/297) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#297` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#297](https://github.com/amihaiemil/docker-java-api/issues/297) is now out of scope

**Pull request merged**
