### PR TITLE
Close #172. Creating new puzzle to create new Auth client

### LINKED ISSUE #172: AuthHttpClient.java:45-46: Start decorating our internal...
The puzzle `99-3f73ab5f` from #99 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/ab0d78ec783de53306d63a66dd459598d58dc8c4/src/main/java/com/amihaiemil/docker/AuthHttpClient.java#L45-L46

The puzzle was created by rultor on 23-May-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by bkuzmic**
PR for #172

### CODE REVIEW

**Comment by bkuzmic** [comment]
@amihaiemil Intellij IDEA has once again "fixed" my imports. Do you have a layout schema for imports?

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this pull request is too small, just 8 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please review this and merge or reject

**Comment by amihaiemil** [comment]
@bkuzmic I formatted the puzzle (it has to be this format, otherwise 0pdd complains) and also referenced the initial Issue in the PR's descritiption. 

Also, for the future, please don't use Github keywords like "closes" or "fixes" since the initial Issue will be closed automatically (by you) and then 0crat will complain: the ticket's reporter has to be the one that closes it :D

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#203` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
