### PR TITLE
#296 fix events() path

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #296 
Fixed URI path.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#298](https://github.com/amihaiemil/docker-java-api/issues/298) is now in scope, role is `REV`

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#298` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#298](https://github.com/amihaiemil/docker-java-api/issues/298) is now out of scope

**Pull request merged**
