### PR TITLE
#58 IT case for Container#rename

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #58 
Started writing Integration tests

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#107](https://github.com/amihaiemil/docker-java-api/issues/107) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#107](https://github.com/amihaiemil/docker-java-api/issues/107) is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1351364245); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by llorllale** [comment]
@amihaiemil build is failing

**Comment by amihaiemil** [comment]
@llorllale It works now. The problem was that the ``hello-world`` image was not present (I added ``docker pull hello-world`` to ``.travis.yml``, so we always have at least that image.

**Comment by amihaiemil** [comment]
@llorllale I'll merge it, because I want to show the unit test in a ticket for docker on Github. It has a strange behaviour: it responds with 404 when the container cannot be created (because the image is missing), instead of 412...

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#107](https://github.com/amihaiemil/docker-java-api/issues/107) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Pull request merged**
