### PR TITLE
Stream :: docker.events()

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #299 

* Docker.events() returns an infinite Stream of JsonObject events (added JavaDocs about the call to ``Stream.limit()`` being mandatory).

### CODE REVIEW

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#338` is not assigned, can't get performer

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Comment by 0crat** [comment]
Election failed: performer was not elected (see footprint for details)

**Pull request merged**
